// This file is used to mock optional dependencies during build
export const safeParseAsync = async () => ({ success: true, data: {} });
export const toJsonSchema = () => ({});
export const object = () => {};
export const string = () => {};
export const number = () => {};
export const boolean = () => {};
export const array = () => {};
export const optional = () => {};
export const nullable = () => {};
export const nullish = () => {};
export const union = () => {};
export const intersect = () => {};
export const record = () => {};
export const tuple = () => {};
export const map = () => {};
export const set = () => {};
export const special = () => {};
export const any = () => {};
export const unknown = () => {};
export const never = () => {};
export const void_ = () => {};
export const literal = () => {};
export const enum_ = () => {};
export const instance = () => {};
export const lazy = () => {};
export const recursive = () => {};
export const brand = () => {};
export const coerce = () => {};
export const transform = () => {};
export const refine = () => {};
export const parse = () => {};
export const safeParse = () => {};
export const flatten = () => {};
export const BaseSchema = class {};
export const BaseSchemaAsync = class {};
export default {};
